### ISSUE TITLE
Self-describing documentation

### ISSUE THREAD

**Issue by GoncaloPataca** [joshstrange/paprika-api#2]
Hi,

It seems this repository is missing some documentation. For example, I have access to the groceries list, but it is not clear whether I can use it to save some state into it or not. Additionally, it’s unclear whether this is an official repo from the Paprika team.

I noticed there haven’t been any updates in 6 years. Is this project still being maintained?

**Comment by joshstrangetp** [comment]
It is not maintained and is not official. It's something I wrote to interact with Paprika's API for an old project.

**Comment by GoncaloPataca** [comment]
Got it, thanks for clarifying. Really cool project in that case.
